apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ar1jnmoqm-python-gitops
  description: This is GitOps manifest for ar1jnmoqm-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ar1jnmoqm-python
    backstage.io/kubernetes-id: ar1jnmoqm-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ar1jnmoqm-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ar1jnmoqm-python
