apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ar1jnmoqm-python
  janus-idp.io/tekton: ar1jnmoqm-python
  backstage.io/kubernetes-id: ar1jnmoqm-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ar1jnmoqm-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
